# Generated by Django 4.1.5 on 2023-01-29 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newblog', '0002_blognew_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognew',
            name='unlikes',
            field=models.ManyToManyField(related_name='unlike_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
