# Generated by Django 4.1.5 on 2023-01-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0005_alter_comment_post_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reply',
        ),
    ]
