# Generated by Django 4.1.5 on 2023-02-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0007_creply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creply',
        ),
    ]
